# Generated by Django 3.0.6 on 2020-06-04 09:00

from django.db import migrations, models
import treasuremap.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_point', treasuremap.fields.LatLongField(max_length=24)),
                ('null_point', treasuremap.fields.LatLongField(blank=True, max_length=24, null=True)),
                ('default_point', treasuremap.fields.LatLongField(default=treasuremap.fields.LatLong(33.000000, 44.000000), max_length=24)),
            ],
        ),
    ]
